#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["psycopg[binary]>=3.1"]
# ///
"""
path-layout measurement — PLAN.md ongoing item 6, "the large-tree path-layout
measurement that decides the final index shape".

WHY THIS EXISTS
    inventory-impl-changeset's 005-data.yaml is a FRESH-INSTALL schema. While no
    database anyone cares about has run it, its index shape can still be edited in
    place; the moment one has, Liquibase pins the changeSet by checksum and any
    change becomes a migration over live rows. This script answers the open
    questions BEFORE that window shuts.

WHAT IT ANSWERS
    Q1  entriesOf() filters with `lower(path_text) LIKE '%needle%'` — a LEADING
        wildcard, which a btree CANNOT serve. idx_data_entries_item_path helps the
        item_id filter and the ORDER BY, but the substring match itself scans every
        row of that medium. Does that matter at real scale, and does it want a
        pg_trgm GIN index instead?
    Q2  Does the path_elements dictionary earn its keep? It bounds storage by
        interning repeated components (src, target, node_modules...). Measure the
        interning ratio and what the ids actually cost.
        NOTE while reading results: as of 2026-08-27 `path_ids` is WRITTEN by the
        insert and the rename UPDATE and READ BY NOTHING — even renamePath matches
        on `path_text LIKE`, not on the id array. So the dictionary is currently
        pure write cost with no read path. That may still be correct (it is the
        append-only substrate a rename rewrites), but weigh it knowingly.
    Q3  findByHash is an equality lookup on a btree. Expected fine; measured anyway
        so "fine" is a number.
    Q4  findMirrorsOf self-joins on (path_hash, hash) but only path_hash is indexed,
        so each candidate is heap-fetched to check `hash`. The first trial run made
        this the SLOWEST query of the five — slower than the substring scan this
        script was written to investigate. A composite (path_hash, hash) is the
        candidate; the script builds it and re-measures.

WHAT IT NEEDS
    Realistic PATHS at volume — depth distribution and component repetition. It does
    NOT need real file contents, real hashes, or real removable media: the hash
    columns are opaque bytes where only cardinality matters, and hashing a large tree
    is the expensive part of this while buying nothing for a LAYOUT question.
    Any big tree you already have works:  --walk /usr   or   find / -type f > paths.txt

USAGE
    ./path-layout-measure.py --walk /usr --dsn postgresql://user:pw@localhost/measure
    ./path-layout-measure.py --paths paths.txt --scales 100000,500000 --dsn ...
    ./path-layout-measure.py --walk ~ --docker          # starts its own throwaway pg

    uv handles the dependency; no venv, no pip. Falls back to plain python3 if
    psycopg is already importable.

SAFETY
    Creates and DROPS a schema named `pathmeasure` in the target database. It never
    touches the public schema, so pointing it at a real inventory database is
    harmless — but point it at a scratch one anyway.
"""
from __future__ import annotations

import argparse
import hashlib
import os
import random
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass, field

try:
    import psycopg
except ImportError:  # pragma: no cover
    sys.exit("psycopg is required. Run with uv (./path-layout-measure.py) or: pip install 'psycopg[binary]'")

SCHEMA = "pathmeasure"

# ---------------------------------------------------------------------------
# DDL — a faithful copy of inventory-impl-changeset 005-data.yaml (+ the minimal
# `items` it references). Kept literal rather than driven through Liquibase so the
# script stays a single scp-able file. If 005-data.yaml changes, change this too.
# ---------------------------------------------------------------------------
DDL = f"""
DROP SCHEMA IF EXISTS {SCHEMA} CASCADE;
CREATE SCHEMA {SCHEMA};
SET search_path TO {SCHEMA};

-- only the columns data_entries actually needs to reference/join
CREATE TABLE items (
  id   varchar(26) PRIMARY KEY,
  name text NOT NULL
);

CREATE TABLE mime_types (
  id   int GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_mime_types PRIMARY KEY,
  name text NOT NULL CONSTRAINT uq_mime_types_name UNIQUE
);

CREATE TABLE path_elements (
  id   bigint GENERATED BY DEFAULT AS IDENTITY CONSTRAINT pk_path_elements PRIMARY KEY,
  name text NOT NULL CONSTRAINT uq_path_elements_name UNIQUE
);

CREATE TABLE data_entries (
  item_id     varchar(26) NOT NULL REFERENCES items(id) ON DELETE CASCADE,
  path_ids    bigint[]    NOT NULL,
  path_hash   bytea       NOT NULL,
  path_text   text        NOT NULL,
  size_bytes  bigint      NOT NULL,
  hash_alg    smallint    NOT NULL,
  hash        bytea       NOT NULL,
  mime_id     int         REFERENCES mime_types(id),
  modified_at timestamptz,
  is_archive  boolean     NOT NULL DEFAULT false,
  CONSTRAINT pk_data_entries PRIMARY KEY (item_id, path_hash)
);

CREATE INDEX idx_data_entries_hash      ON data_entries (hash_alg, hash);
CREATE INDEX idx_data_entries_path_hash ON data_entries (path_hash);
CREATE INDEX idx_data_entries_item_path ON data_entries (item_id, path_text);
"""

# The three production queries, verbatim in shape from PgDataSystem.
Q_SCOPE_SUBSTRING = """
SELECT path_text, size_bytes, hash_alg, hash, modified_at, is_archive,
       (SELECT name FROM mime_types m WHERE m.id = e.mime_id) AS mime_name
  FROM data_entries e
 WHERE item_id=%s AND (%s = '' OR lower(path_text) LIKE '%%' || %s || '%%')
 ORDER BY path_text OFFSET 0 LIMIT 100
"""
Q_SCOPE_NOFILTER = """
SELECT path_text, size_bytes FROM data_entries e
 WHERE item_id=%s ORDER BY path_text OFFSET 0 LIMIT 100
"""
Q_SUMMARY = """
SELECT count(*) AS n, coalesce(sum(size_bytes),0) AS bytes,
       count(*) FILTER (WHERE is_archive) AS archives
  FROM data_entries WHERE item_id=%s
"""
Q_BY_HASH = """
SELECT e.item_id, e.path_text, e.size_bytes, i.name AS item_name
  FROM data_entries e JOIN items i ON i.id = e.item_id
 WHERE e.hash_alg=%s AND e.hash=%s
 ORDER BY i.name, e.path_text
"""
Q_MIRRORS = """
SELECT o.item_id, o.path_text, o.size_bytes, i.name AS item_name
  FROM data_entries o
  JOIN data_entries m ON m.path_hash = o.path_hash AND m.hash = o.hash
  JOIN items i ON i.id = o.item_id
 WHERE m.item_id = %s AND o.item_id <> %s
 ORDER BY i.name, o.path_text
"""


@dataclass
class Harvest:
    paths: list[str]
    walked_from: str
    depth_hist: dict[int, int] = field(default_factory=dict)

    def report(self) -> str:
        if not self.paths:
            return "  (no paths)"
        depths = sorted(self.depth_hist.items())
        avg = sum(d * n for d, n in depths) / len(self.paths)
        comps = sum(d for d, n in depths for _ in range(n))
        return (f"  source          {self.walked_from}\n"
                f"  paths           {len(self.paths):,}\n"
                f"  avg depth       {avg:.2f} components\n"
                f"  total comps     {comps:,}\n"
                f"  depth spread    " + ", ".join(f"{d}:{n:,}" for d, n in depths[:12]))


def harvest(walk: str | None, paths_file: str | None, limit: int) -> Harvest:
    out: list[str] = []
    hist: dict[int, int] = {}
    src = walk or paths_file or "?"

    def note(rel: str) -> bool:
        rel = rel.lstrip("/")
        if not rel:
            return True
        out.append(rel)
        d = rel.count("/") + 1
        hist[d] = hist.get(d, 0) + 1
        return len(out) < limit

    if paths_file:
        with open(paths_file, "r", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if line and not note(line):
                    break
    else:
        root = os.path.abspath(walk or ".")
        stop = False
        for dirpath, dirnames, filenames in os.walk(root, onerror=lambda e: None):
            dirnames[:] = [d for d in dirnames if not os.path.islink(os.path.join(dirpath, d))]
            for fn in filenames:
                rel = os.path.relpath(os.path.join(dirpath, fn), root)
                if not note(rel):
                    stop = True
                    break
            if stop:
                break
    return Harvest(out, src, hist)


MIMES = ["application/octet-stream", "text/plain", "image/jpeg", "video/mp4", "application/pdf",
         "text/x-java", "application/zip", "audio/flac", "text/html", "application/json"]


def build_rows(h: Harvest, media: int, dup_ratio: float, rng: random.Random):
    """Assign paths to synthetic media; duplicate a fraction across media with the
    SAME content hash, which is what makes findByHash/findMirrors measurable."""
    item_ids = [f"01MEASURE{n:017d}"[:26] for n in range(media)]
    rows = []
    dup_pool: list[tuple[str, bytes]] = []
    for path in h.paths:
        owner = rng.randrange(media)
        content = hashlib.sha256(path.encode("utf-8", "replace")).digest()
        rows.append((item_ids[owner], path, content))
        if rng.random() < dup_ratio:
            dup_pool.append((path, content))
    # place duplicates on a DIFFERENT medium, same path AND same content: the mirror case
    for path, content in dup_pool:
        other = rng.randrange(media)
        rows.append((item_ids[other], path, content))
    # dedupe on (item, path) — the PK is (item_id, path_hash)
    seen = set()
    final = []
    for item, path, content in rows:
        key = (item, path)
        if key in seen:
            continue
        seen.add(key)
        final.append((item, path, content))
    rng.shuffle(final)
    return item_ids, final


def load(conn, item_ids, rows, rng: random.Random) -> dict:
    cur = conn.cursor()
    cur.execute(f"SET search_path TO {SCHEMA}")
    cur.executemany("INSERT INTO items (id, name) VALUES (%s, %s)",
                    [(i, f"medium-{n}") for n, i in enumerate(item_ids)])
    cur.executemany("INSERT INTO mime_types (name) VALUES (%s)", [(m,) for m in MIMES])
    cur.execute("SELECT id, name FROM mime_types")
    mime_ids = [r[0] for r in cur.fetchall()]

    # intern path components exactly as PgDataSystem.intern does: distinct names only
    t0 = time.perf_counter()
    components: set[str] = set()
    for _, path, _ in rows:
        components.update(path.split("/"))
    with cur.copy("COPY path_elements (name) FROM STDIN") as cp:
        for name in components:
            cp.write_row((name,))
    cur.execute("SELECT name, id FROM path_elements")
    comp_id = dict(cur.fetchall())
    intern_secs = time.perf_counter() - t0

    t0 = time.perf_counter()
    with cur.copy("COPY data_entries (item_id, path_ids, path_hash, path_text, size_bytes,"
                  " hash_alg, hash, mime_id, is_archive) FROM STDIN") as cp:
        for item, path, content in rows:
            parts = path.split("/")
            cp.write_row((item, [comp_id[p] for p in parts],
                          hashlib.sha256(path.encode("utf-8", "replace")).digest(),
                          path, rng.randrange(1, 1 << 32), 1, content,
                          mime_ids[rng.randrange(len(mime_ids))], False))
    load_secs = time.perf_counter() - t0
    conn.commit()
    cur.execute("ANALYZE data_entries")
    cur.execute("ANALYZE path_elements")
    conn.commit()
    return {"components": len(components), "intern_secs": intern_secs, "load_secs": load_secs}


def explain(cur, sql, params) -> tuple[float, str]:
    cur.execute("EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT) " + sql, params)
    lines = [r[0] for r in cur.fetchall()]
    ms = 0.0
    for ln in lines:
        if ln.strip().startswith("Execution Time:"):
            ms = float(ln.split(":")[1].strip().split(" ")[0])
    plan = lines[0].strip()
    scan = next((l.strip() for l in lines if "Scan" in l), plan)
    return ms, scan


def measure(conn, item_ids, rows, args) -> None:
    cur = conn.cursor()
    cur.execute(f"SET search_path TO {SCHEMA}")
    probe_item = item_ids[0]
    # a needle guaranteed to exist somewhere, taken from a real path component
    sample = next((p for _, p, _ in rows if "/" in p), rows[0][1])
    needle = sample.split("/")[-1][:8].lower() or "a"
    cur.execute("SELECT hash_alg, hash FROM data_entries LIMIT 1")
    alg, a_hash = cur.fetchone()

    print("\n  QUERY                                    plan                                     ms")
    print("  " + "-" * 92)

    def row(label, sql, params):
        ms, scan = explain(cur, sql, params)
        print(f"  {label:<40} {scan[:38]:<38} {ms:>8.2f}")
        return ms

    row("entriesOf (no filter)", Q_SCOPE_NOFILTER, (probe_item,))
    before = row("entriesOf SUBSTRING  [the question]", Q_SCOPE_SUBSTRING, (probe_item, needle, needle))
    row("summaryOf", Q_SUMMARY, (probe_item,))
    row("findByHash", Q_BY_HASH, (alg, a_hash))
    mirrors_ms = row("findMirrorsOf", Q_MIRRORS, (probe_item, probe_item))

    # --- the candidate fix -------------------------------------------------
    print("\n  adding pg_trgm GIN on lower(path_text) and re-measuring the substring query...")
    try:
        cur.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
        conn.commit()
    except Exception as e:
        conn.rollback()
        print(f"  !! pg_trgm unavailable ({e.__class__.__name__}); skipping the comparison")
        return
    t0 = time.perf_counter()
    cur.execute("CREATE INDEX idx_trgm ON data_entries USING gin (lower(path_text) gin_trgm_ops)")
    conn.commit()
    build = time.perf_counter() - t0
    cur.execute("ANALYZE data_entries")
    conn.commit()
    after = row("entriesOf SUBSTRING  [with trgm]", Q_SCOPE_SUBSTRING, (probe_item, needle, needle))
    cur.execute(f"SELECT pg_size_pretty(pg_relation_size('{SCHEMA}.idx_trgm'))")
    size = cur.fetchone()[0]
    print(f"\n  trgm index: built in {build:.1f}s, {size} on disk")
    if after > 0:
        verdict = "WORTH IT" if before / max(after, 0.001) > 2 else "NOT clearly worth it"
        print(f"  substring query {before:.2f}ms -> {after:.2f}ms  ({before/max(after,0.001):.1f}x)  => {verdict}")

    # --- second candidate: findMirrorsOf ----------------------------------
    # The self-join matches on (path_hash, hash) but only path_hash is indexed, so
    # every candidate row is heap-fetched to check `hash`. A composite covering both
    # lets the join filter in the index. Discovered by the first trial run, where
    # findMirrorsOf was the SLOWEST query measured — slower than the substring scan
    # this script was originally written to investigate.
    print("\n  adding (path_hash, hash) and re-measuring findMirrorsOf...")
    m_before = mirrors_ms
    cur.execute("CREATE INDEX idx_mirror ON data_entries (path_hash, hash)")
    conn.commit()
    cur.execute("ANALYZE data_entries")
    conn.commit()
    m_after = row("findMirrorsOf  [with composite]", Q_MIRRORS, (probe_item, probe_item))
    cur.execute(f"SELECT pg_size_pretty(pg_relation_size('{SCHEMA}.idx_mirror'))")
    m_size = cur.fetchone()[0]
    if m_after > 0:
        v = "WORTH IT" if m_before / max(m_after, 0.001) > 2 else "NOT clearly worth it"
        print(f"\n  mirror index: {m_size} on disk")
        print(f"  findMirrorsOf {m_before:.2f}ms -> {m_after:.2f}ms  ({m_before/max(m_after,0.001):.1f}x)  => {v}")


def storage(conn) -> None:
    cur = conn.cursor()
    cur.execute(f"SET search_path TO {SCHEMA}")
    print("\n  STORAGE")
    cur.execute("""
        SELECT relname, pg_size_pretty(pg_total_relation_size(c.oid)) tot,
               pg_size_pretty(pg_relation_size(c.oid)) heap,
               pg_size_pretty(pg_indexes_size(c.oid)) idx
          FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
         WHERE n.nspname=%s AND c.relkind='r' ORDER BY pg_total_relation_size(c.oid) DESC
    """, (SCHEMA,))
    print(f"    {'table':<18} {'total':>10} {'heap':>10} {'indexes':>10}")
    for name, tot, heap, idx in cur.fetchall():
        print(f"    {name:<18} {tot:>10} {heap:>10} {idx:>10}")
    cur.execute("SELECT pg_size_pretty(sum(octet_length(path_text))::bigint),"
                " pg_size_pretty(sum(octet_length(path_ids::text))::bigint) FROM data_entries")
    text_b, ids_b = cur.fetchone()
    print(f"\n    path_text total  {text_b}")
    print(f"    path_ids  total  {ids_b}   <- written, currently read by nothing (see header)")


def start_docker() -> tuple[str, str | None]:
    if not shutil.which("docker"):
        sys.exit("--docker needs docker on PATH")
    name = "pathmeasure-pg"
    subprocess.run(["docker", "rm", "-f", name], capture_output=True)
    subprocess.run(["docker", "run", "-d", "--name", name, "-e", "POSTGRES_PASSWORD=x",
                    "-e", "POSTGRES_DB=measure", "-p", "55440:5432", "postgres:16-alpine"],
                   check=True, capture_output=True)
    for _ in range(60):
        r = subprocess.run(["docker", "exec", name, "pg_isready", "-U", "postgres"], capture_output=True)
        if r.returncode == 0:
            break
        time.sleep(1)
    return "postgresql://postgres:x@localhost:55440/measure", name


def main() -> None:
    ap = argparse.ArgumentParser(description="path-layout index measurement (PLAN.md ongoing item 6)")
    src = ap.add_mutually_exclusive_group(required=True)
    src.add_argument("--walk", help="directory to harvest real paths from (e.g. /usr)")
    src.add_argument("--paths", help="file of newline-separated paths (e.g. find output)")
    ap.add_argument("--dsn", help="postgres DSN; omit with --docker")
    ap.add_argument("--docker", action="store_true", help="start a throwaway postgres:16 container")
    ap.add_argument("--scales", default="100000,500000", help="row counts to measure at")
    ap.add_argument("--media", type=int, default=8, help="synthetic media (items) to spread paths over")
    ap.add_argument("--dup-ratio", type=float, default=0.15, help="fraction duplicated across media")
    ap.add_argument("--seed", type=int, default=20260827)
    ap.add_argument("--keep", action="store_true", help="leave the docker container running")
    args = ap.parse_args()

    scales = [int(s) for s in args.scales.split(",") if s.strip()]
    rng = random.Random(args.seed)
    container = None
    dsn = args.dsn
    if args.docker:
        dsn, container = start_docker()
    if not dsn:
        sys.exit("need --dsn or --docker")

    biggest = max(scales)
    print("=" * 96)
    print("  PATH-LAYOUT MEASUREMENT — deciding 005-data.yaml's final index shape")
    print("=" * 96)
    print("\n  HARVEST")
    h = harvest(args.walk, args.paths, biggest)
    print(h.report())
    if len(h.paths) < min(scales):
        print(f"\n  !! only {len(h.paths):,} paths available; smallest requested scale is {min(scales):,}")
        print("     point --walk at a bigger tree, or lower --scales")

    try:
        for scale in scales:
            subset = h.paths[:scale]
            if not subset:
                continue
            sub = Harvest(subset, h.walked_from, h.depth_hist)
            print("\n" + "=" * 96)
            print(f"  SCALE: {len(subset):,} source paths, {args.media} media, dup-ratio {args.dup_ratio}")
            print("=" * 96)
            item_ids, rows = build_rows(sub, args.media, args.dup_ratio, rng)
            with psycopg.connect(dsn, autocommit=False) as conn:
                conn.execute(DDL)
                conn.commit()
                stats = load(conn, item_ids, rows, rng)
                uniq = stats["components"]
                total_comps = sum(p.count("/") + 1 for p in subset)
                print(f"\n  ROWS {len(rows):,}  (incl. cross-media duplicates)")
                print(f"  loaded in {stats['load_secs']:.1f}s; interning {stats['intern_secs']:.1f}s")
                print("\n  DICTIONARY  [Q2: does interning earn its keep?]")
                print(f"    distinct components   {uniq:,}")
                print(f"    component references  {total_comps:,}")
                print(f"    interning ratio       {total_comps/max(uniq,1):.1f}x reuse")
                storage(conn)
                measure(conn, item_ids, rows, args)
    finally:
        if container and not args.keep:
            subprocess.run(["docker", "rm", "-f", container], capture_output=True)
            print(f"\n  (removed container {container})")
        elif container:
            print(f"\n  (container {container} left running at {dsn})")

    print("\n" + "=" * 96)
    print("  Read the substring row first: if it is a Seq Scan whose ms grows with scale,")
    print("  005-data.yaml wants a pg_trgm GIN index and this is the moment to add it.")
    print("=" * 96)


if __name__ == "__main__":
    main()
